Init Check for the config and typo corrections
IBM/packer-plugin-ibmcloud pull request #76
Opened 2023-04-18 11:33 UTC by BShrivastav

- Added redundancy check for custom image.
- Removed the crash.log
- Typo correction with README.md

2023-05-01 19:20 UTC, astha-jain commented on builder/ibmcloud/vpc/step_get_subnet_info.go
> +		err := fmt.Errorf("[ERROR] Error VPCs of provided security group %s, and subnet's VPC %s, doesnot match", secGrpVPC, vpcId)
Please use the security group and subnet connected to VPC id %s

2023-05-01 19:22 UTC, astha-jain commented on builder/ibmcloud/vpc/step_verify_input.go
> +	ui.Say("Region verified, check Passed")
need to rephrase this

2023-05-01 20:56 UTC, astha-jain commented on builder/ibmcloud/vpc/step_verify_input.go
> +			err := fmt.Errorf("[ERROR] Error fetching resource group : %s: %s", config.ResourceGroupID, err)
Incorrect error message.

2023-05-01 20:56 UTC, astha-jain commented on builder/ibmcloud/vpc/step_verify_input.go
> +			ui.Say(fmt.Sprintf("Continuing with resource group : %s", *result.Name))
Do we need this?

2023-05-01 20:57 UTC, astha-jain commented on builder/ibmcloud/vpc/step_verify_input.go
> +	ui.Say(fmt.Sprintf("Checking the custom image: %s for redundancy", config.ImageName))
same, do we need this to be displayed?

2023-05-01 20:59 UTC, astha-jain commented on builder/ibmcloud/vpc/step_verify_input.go
> +		err := fmt.Errorf("[ERROR] Existing custom image found with name: %s", config.ImageName)
Maybe "Could not find an image with the name %s"

2023-05-01 21:01 UTC, astha-jain commented on builder/ibmcloud/vpc/step_verify_input.go
> +			ui.Say(fmt.Sprintf("Using provided security group: %s with security_group_id: %s", *secGrp.Name, *secGrp.ID))
Again, do we need this?

2023-05-15 05:47 UTC, deepaksibm approved these changes

2023-05-15 11:17 UTC, ujjwal-ibm requested changes

2023-05-15 11:17 UTC, ujjwal-ibm commented on builder/ibmcloud/vpc/step_get_subnet_info.go
> +	secGrpVPC := state.Get("user_sec_grp_vpc")
This is throwing an error saying security group is not in same vpc. Even when not passing sg id

2023-05-16 15:46 UTC, astha-jain approved these changes

2023-05-17 10:11 UTC, merged