Added support for user-tags
IBM/packer-plugin-ibmcloud pull request #85
Opened 2023-05-25 19:32 UTC by BShrivastav

User tag support added.
Default tag  `creator: ibm-packer-plugin`  is added with every run to intimate creator as packer for the custom image.

2023-06-12 21:03 UTC, astha-jain reviewed
Suggested change

2023-06-23 11:37 UTC, ujjwal-ibm commented on builder/ibmcloud/vpc/config.go
> +	// if PKR_GLB_SRCH_TAG_URL
removed

2023-06-23 11:37 UTC, ujjwal-ibm commented on builder/ibmcloud/vpc/step_capture_image.go
> +		err := fmt.Errorf("[ERROR] Error creating global tagging client options: %s", errOpt)
changed

2023-06-23 11:37 UTC, ujjwal-ibm commented on README.md
> +tags | list |  List of tags that you want for your image. Tags can help you find the image more easily later. Tags can be made as `key:value` pair or in `label` format. Optional.
changed

2023-06-23 11:38 UTC, ujjwal-ibm approved these changes

2023-06-25 19:05 UTC, astha-jain requested changes

2023-06-25 19:05 UTC, astha-jain commented on builder/ibmcloud/vpc/config.go
> +	GTEndpoint                string `mapstructure:"gt_endpoint_url"`
Please ghost instead of gt

2023-06-25 19:05 UTC, astha-jain commented on builder/ibmcloud/vpc/step_verify_input.go
> +				return multistep.ActionHalt
If tagging failed, can we throw an error and not fail the entire run, I believe `return multistep.ActionHalt` will fail the step. What do you think?

2023-06-25 19:05 UTC, astha-jain commented on developer/README.md
> +   gt_endpoint_url | string | Configure URL for Global Tagging test environments. Optional.
lets use ghost_endpoint_url please.

2023-07-06 16:46 UTC, astha-jain approved these changes
Looks good

2023-07-06 16:46 UTC, merged